name: aura_one
description: AURA ONE - The Unified AI Operating System for Hospitals.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  socket_io_client: ^2.0.3
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  shared_preferences: ^2.2.2

  permission_handler: ^11.0.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hospital_map.png
